# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account-key.json
    volumes:
      - ./credentials:/app/credentials
      - ./backend:/app
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend-chainlit
    ports:
      - "8001:8001"
    environment:
      - API_BASE_URL=http://backend:8080
    volumes:
      - ./frontend-chainlit:/app
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
