# deployment/cloudbuild.yaml
steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/avestoai-backend', './backend']

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/avestoai-backend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'avestoai-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/avestoai-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

  # Build and deploy Chainlit frontend
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend-chainlit
        pip install -r requirements.txt
        chainlit run app.py --host 0.0.0.0 --port 8080 &

  # Deploy Flutter web app
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend-flutter
        flutter build web
        gcloud app deploy --quiet

substitutions:
  _REGION: 'us-central1'

options:
  machineType: 'E2_HIGHCPU_8'
